applications/virtualization/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
from .views import *

app_name = 'virtualization'
urlpatterns = [
	path('', projects.as_view(), name = 'projects'),
	path('tcloud/project/<slug:slug>', projectdetail.as_view(), name = 'projectdetail'),
	path('tcloud/hypervisor', hypervisor.as_view(), name = 'hypervisor'),
	path('tcloud/vm', vm.as_view(), name = 'vm'),
	# path('todomark/<int:id>/update_mark_todo', views.update_mark_todo, name = 'update_mark_todo'),
	# path('note/<int:id>/add_note_in_project', views.add_note_in_project, name = 'add_note_in_project'),
	# path('delete/<int:id>/note', views.noteDelete, name='noteDelete'),
	# path('budget/<int:id>/add_budget_in_project', views.add_budget_in_project, name = 'add_budget_in_project'),
	path('tcloud/todo/<int:id>/todofinished', views.todofinished, name = 'todofinished'),
	# path('milestone/<int:id>/milestonefinished', views.milestonefinished, name = 'milestonefinished'),
	# path('add/project', projectCreate.as_view(), name = 'projectCreate'),
	# path('add/notestoproject', TodoProjectCreate.as_view(), name = 'TodoProjectCreate'),
	# path('activate_milestone/<int:id>/project', views.activate_milestone, name = 'activate_milestone'),
	# path('deactivate_milestone/<int:id>/project', views.deactivate_milestone, name = 'deactivate_milestone'),
]

virt_dev/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('applications.virtualization.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('explorer/', include('explorer.urls')),
]

applications/virtualization/models.py
from django.db import models
from autoslug import AutoSlugField
from tinymce.models import HTMLField
from django_countries.fields import CountryField
from django.contrib.auth.models import User


class Provider(models.Model):
    provider_name = models.CharField(max_length=255, verbose_name='Proveedor')

    def __str__(self):
        return self.provider_name

    class Meta:
        ordering = ['-id']

class Site(models.Model):
    site_name = models.CharField(max_length=255, verbose_name='Sitio')

    def __str__(self):
        return self.site_name

    class Meta:
        ordering = ['-id']

class Tenant(models.Model):
    tenant_hostname = models.CharField(max_length=255, verbose_name='Hostname')
    site = models.ForeignKey(Site, on_delete=models.CASCADE)
    ip_inband = models.GenericIPAddressField(blank=True, null=True)
    ip_outband = models.GenericIPAddressField(blank=True, null=True)

    def __str__(self):
        return self.tenant_hostname

    class Meta:
        ordering = ['-id']

class Area(models.Model):
    area_title = models.CharField(max_length=255, verbose_name='Area')
    responsable = models.CharField(max_length=255, verbose_name='Lider Area')

    def __str__(self):
        return self.area_title

    class Meta:
        verbose_name = 'Area'
        verbose_name_plural = 'Areas'
        ordering = ['-id']

class Collaborator(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Nombre')
    country = CountryField(blank_label='(seleccionar país)', verbose_name='País')
    area = models.ForeignKey(Area, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return "%s %s" % ( self.user.first_name, self.user.last_name )

    class Meta:
        verbose_name = 'Colaborador'
        verbose_name_plural = 'Colaboradores'
        ordering = ['-id']

class Project(models.Model):
    project_title = models.CharField(max_length=200, verbose_name='Titulo')
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE, verbose_name='Proveedor')
    year = models.IntegerField(null=True, verbose_name='Año Proyectado')
    country = CountryField(verbose_name='Pais')
    # slug = AutoSlugField(populate_from=lambda instance: "{0}-{1}".format(instance.project_title, instance.country), always_update=True, null=True)
    slug = AutoSlugField(populate_from='project_title_country', always_update=True, null=True)
    collaborator = models.ManyToManyField(Collaborator, related_name='Colaborador', verbose_name='Colaboradores')
    resume = HTMLField()
    pub_date = models.DateTimeField(auto_now_add=True)
    planned_date = models.DateField(null=True, verbose_name='Fecha Planificada')
    done_date = models.DateField(null=True, verbose_name='Fecha de termino Real', blank=True)
    state = models.BooleanField(blank=True, null=True, default=False, verbose_name='Terminando?')

    def project_title_country(self):
        return '%s %s' % (self.project_title, self.country.name)

    def __str__(self):
        return '%s %s' % (self.project_title, self.country)

    class Meta:
        verbose_name = 'Proyecto'
        ordering = ['-id']

class VM(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    vm_name = models.CharField(max_length=200, verbose_name='Nombre VM')
    slug = AutoSlugField(populate_from='vm_name', always_update=True, null=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    state = models.BooleanField(blank=True, null=True, default=False, verbose_name='Activa')
    vcpu_total = models.IntegerField(null=True, verbose_name='vCPU')
    ram_total = models.IntegerField(null=True, verbose_name='RAM')
    internal_disk_total = models.IntegerField(null=True, verbose_name='Disco IN')
    external_disk_total = models.IntegerField(null=True, blank=True, verbose_name='Disco EX')
    tenant = models.ForeignKey(Tenant, on_delete=models.CASCADE, null=True, blank=True)
    # site = models.ForeignKey(Site, on_delete=models.CASCADE)

    def __str__(self):
        return self.vm_name

    class Meta:
        verbose_name = 'Virtual Machine'
        ordering = ['id']

class Network(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    network_name = models.CharField(max_length=200, verbose_name='Nombre')
    ip_address_mask = models.CharField(max_length=200, verbose_name='IP/MASK')
    vlan_id = models.CharField(max_length=200, verbose_name='VLAN')
    vrrp_vip = models.GenericIPAddressField(blank=True, null=True)
    vrrp_r1 = models.GenericIPAddressField(blank=True, null=True)
    vrrp_r2 = models.GenericIPAddressField(blank=True, null=True)
    vrf_name = models.CharField(max_length=200, verbose_name='VRF')
    site = models.ForeignKey(Site, on_delete=models.CASCADE)

    def __str__(self):
        return '%s %s %s' % (self.site, self.project, self.network_name)

class Port(models.Model):
    vm = models.ForeignKey(VM, on_delete=models.CASCADE)
    network = models.ForeignKey(Network, on_delete=models.CASCADE)
    ip_add = models.GenericIPAddressField(blank=True, null=True)

    def __str__(self):
        return self.ip_add

class Descriptor(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    descriptor_name = models.CharField(max_length=200, verbose_name='Titulo')
    descriptor = HTMLField()

class Todo(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True, blank=True)
    todo_title = models.CharField(max_length=200, verbose_name='Titulo')
    slug = AutoSlugField(populate_from='todo_title', always_update=True, null=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    deadline_date = models.DateField(null=True, verbose_name='Fecha planificación')
    collaborator = models.ForeignKey(Collaborator, on_delete=models.CASCADE, verbose_name='Encargado',null=True, blank=True)
    done_date = models.DateField(null=True, verbose_name='Fecha termino', blank=True)
    state = models.BooleanField(blank=True, null=True, default=False, verbose_name='Terminado')
    progress = models.IntegerField(blank=True, null=True, default=0)
    ordering_position = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return self.todo_title

    class Meta:
        verbose_name = 'Tareas de Proyecto'
        ordering = ['ordering_position']

    def diff_days(self):
        delta = self.deadline_date - self.done_date
        # print(delta.days)
        return delta.days > -5

applications/virtualization/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Project, Tenant, Todo, VM
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.db.models import Q
import datetime
from django.db.models.functions import Round
from django.db.models import Count
from django.db.models.functions.comparison import NullIf
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin


class projects(ListView):
    model = Project
    template_name = 'projectlist.html'
    ordering = ['project_title']
    paginate_by = 10

    queryset = Project.objects.annotate(
        todo_done=Round(Count('todo', filter=Q(todo__state=True)) * 100.0 / NullIf(Count('todo'), 0)),
        todo_left=Round(Count('todo', filter=Q(todo__state=False)) * 100.0 / NullIf(Count('todo'), 0)),
    )

    def get_queryset(self, *args, **kwargs):
        context = super().get_queryset(*args, **kwargs)
        search = self.request.GET.get('buscar', None)

        if search:
            context = context.filter(
				Q(project_title__icontains = search) |
				Q(resume__icontains = search) |
                Q(provider__provider_name__icontains = search)
			).distinct()
        return context

class projectdetail(LoginRequiredMixin, DetailView):
    model = Project
    template_name = 'projectdetail.html'
    slug_field = 'slug'

    def get_context_data(self, *args, **kwargs):
        context = super(projectdetail, self).get_context_data(**kwargs)

        '''Rescatar todos las tareas del pryecto'''
        project = self.get_object()
        progress_field = project.todo_set.all()
        '''Listar el campo progress'''
        progress = []
        for todos in progress_field:
            progress.append(todos.progress)
        '''eliminar los NoneType de la lista'''
        progress_not_none = [x for x in progress if x is not None]
        '''Sumar la lista'''
        sum_progress = 0
        for num in progress_not_none:
            sum_progress += num
        ''''''

        if Todo.objects.filter(project=self.object).count() == 0:
            return context
        else:
            if Todo.objects.filter(project=self.object).filter(state=True).count() * 100 / Todo.objects.filter(
                    project=self.object).count() != 100:
                project.state = False
                project.save()
            else:
                project.state = True
                project.save()
        context['get_percentage_done'] = Todo.objects.filter(project=self.object).filter(
            state=True).count() * 100 / Todo.objects.filter(project=self.object).count()
        context['get_percentage_left'] = Todo.objects.filter(project=self.object).filter(
            state=False).count() * 100 / Todo.objects.filter(project=self.object).count()
        context['progress'] = sum_progress
        context['left_progress'] = 100 - sum_progress
        context['todo_done'] = Todo.objects.filter(project=self.object).filter(state=True).count()
        context['todo_total'] = Todo.objects.filter(project=self.object).all().count()

        return context

class hypervisor(ListView):
    model = Tenant
    template_name = 'hypervisorlist.html'
    ordering = ['tenant_hostname']
    # paginate_by = 10

class vm(ListView):
    model = VM
    template_name = 'vmlist.html'
    ordering = ['vm_name']

def todofinished(request, id):
    todo = get_object_or_404(Todo, id=id)

    todo.state = True
    todo.done_date = datetime.date.today()
    todo.save()

    project = todo.project
    all_todo = project.todo_set.all()
    done_todo = all_todo.filter(state=True).count() * 100 / all_todo.count()
    if done_todo == 100:
        project.state = True
        project.done_date = datetime.date.today()
        project.save()
        messages.add_message(request, messages.INFO,
                             'Excelente, has finalizado este proyecto ')
    else:
        project.state = False
        project.save()
    # print(done_todo)

    return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

applications/virtualization/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>TCLOUD | Servidores</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/offcanvas-navbar/">



    <!-- Bootstrap core CSS -->
<link href="https://getbootstrap.com/docs/5.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">

<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .page-item.active .page-link {
          color: #fff !important;
          background-color: #000 !important;
          border-color: #000 !important;
      }

      .page-link {
          color: #000 !important;
          background-color: #fff !important;
          border: 1px solid #dee2e6 !important;
      }

      .page-link:hover {
          color: #fff !important;
          background-color: #000 !important;
          border-color: #000 !important;
      }

      .table {white-space:nowrap}
      
    </style>


    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/5.1/examples/offcanvas-navbar/offcanvas.css" rel="stylesheet">
  </head>
  <body class="bg-light">

<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'virtualization:projects' %}">Proyectos</a>
    <button class="navbar-toggler p-0 border-0" type="button" id="navbarSideCollapse" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'admin:index' %}">Admin Panel</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'virtualization:hypervisor' %}">Hypervisores</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'virtualization:vm' %}">Virtual Machines</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'explorer_index' %}">SQL Explorer</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Salir</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false">Settings</a>
          <ul class="dropdown-menu" aria-labelledby="dropdown01">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" method="get" action="{% url 'virtualization:projects' %}">
        <input class="form-control me-2" type="search" name="buscar" placeholder="Buscar proyecto" aria-label="Buscar proyecto">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block body %}
{% endblock %}



  </body>
  <script src="https://getbootstrap.com/docs/5.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <script src="https://getbootstrap.com/docs/5.1/examples/offcanvas-navbar/offcanvas.js"></script>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> -->
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
    {% block script %}
    {% endblock %}
</html>

applications/virtualization/templates/hypervisorlist.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block body %}
<main class="container">
  <div class="d-flex align-items-center p-3 my-3 text-white bg-dark rounded shadow-sm">
    <ul class="nav nav-pills nav-fill">
      <li class="nav-item">
        <a class="nav-link disabled h6 mb-0 text-white lh-1">Tenants y Servidores TCLOUD</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'admin:virtualization_tenant_add' %}">
          <button type="button" class="btn btn-primary btn-sm">Agregar</button></a>
      </li>
    </ul>
  </div>

  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <div class="table-responsive">
      <table class="table table-striped table-sm" id="sortTableTenant">
        <thead>
          <tr>
            <th scope="col">Hostname</th>
            <th scope="col">Sitio</th>
            <th scope="col">IP InBand</th>
            <th scope="col">IP OutBand</th>
          </tr>
        </thead>
        <tbody>
          {% for tenant in object_list %}
          <tr>
            <td>{{tenant.tenant_hostname}}</td>
            <td>{{tenant.site}}</td>
            <td>{{tenant.ip_inband}}</td>
            <td>{{tenant.ip_outband}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</main>
{% endblock %}

  </body>
  {% block script %}
        <script>

          $('#sortTableTenant').DataTable({
              "language": {
                  "url": "{% static 'js/vm_datatables.js' %}"
              },
              "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "todos"]],
              "pageLength": 10,
              "order": []
          });
        </script>
  {% endblock %}
</html>

applications/virtualization/templates/projectlist.html
{% extends 'base.html' %}
{% load humanize %}
{% block body %}

<main class="container">
  <div class="d-flex align-items-center p-3 my-3 text-white bg-dark rounded shadow-sm">
    <div class="lh-1">
      <h1 class="h6 mb-0 text-white lh-1">Lista de Proyectos</h1>
      <small>TCLOUD</small>
    </div>
  </div>

  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <div class="table-responsive">

      {% for project in object_list %}
      <a href="{% url 'virtualization:projectdetail' project.slug %}" class="text-decoration-none">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">

              {{ project.project_title|upper }}
              {{ project.country.name|upper}}

          </h5>
          <p class="card-text">
            <div class="progress">
                {% if project.todo_done == 100 %}
                <div class="progress-bar progress-bar-striped progress-bar-animated massive-font"
                     role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0"
                     aria-valuemax="100">
                    Proyecto completado
                </div>
                {% else %}
                <div class="progress-bar progress-bar-striped progress-bar-animated massive-font"
                     role="progressbar" style="width: {{project.todo_done|floatformat:0|intcomma}}%"
                     aria-valuenow="{{project.todo_done|floatformat:0|intcomma}}" aria-valuemin="0"
                     aria-valuemax="100">
                    {{ project.todo_done|floatformat:0|intcomma}}%
                </div>
                {% endif %}

            </div>
          </div>
        </div>
      </a>
      <br>
      {% endfor %}

    </div>
  </div>
</main>
{% endblock %}

applications/virtualization/templates/vmlist.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block body %}
<main class="container">
  <div class="d-flex align-items-center p-3 my-3 text-white bg-dark rounded shadow-sm">
    <ul class="nav nav-pills nav-fill">
      <li class="nav-item">
        <a class="nav-link disabled h6 mb-0 text-white lh-1">Lista de VM</a>
      </li>
      <!-- <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'admin:virtualization_tenant_add' %}">Agregar</a>
      </li> -->
    </ul>
  </div>

  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <div class="table-responsive">
      <table class="table table-striped table-sm" id="sortTablevm">
        <thead>
          <tr>
            <th scope="col">Hostname</th>
            <th scope="col">Sitio</th>
            <th scope="col">Proyecto</th>
            <th scope="col">vCPU</th>
            <th scope="col">RAM</th>
            <th scope="col">Disco</th>
            <th scope="col">Hypervisor</th>
          </tr>
        </thead>
        <tbody>
          {% for vm in object_list %}
          <tr>
            <td>{{vm.vm_name}}</td>
            <td>{{vm.site}}</td>
            <td>{{vm.project}}</td>
            <td>{{vm.vcpu_total}}</td>
            <td>{{vm.ram_total}}</td>
            <td>int[{{vm.internal_disk_total}}]-ext[{{vm.external_disk_total}}]</td>
            <td>{{vm.tenant}}</td>

          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</main>
{% endblock %}

  </body>
  {% block script %}
        <script>
        $('#sortTablevm').DataTable({
            "language": {
                "url": "{% static 'js/vm_datatables.js' %}"
            },
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "todos"]],
            "pageLength": 10,
            "order": []
        });
      </script>
  {% endblock %}
</html>